#!/usr/bin/env zsh

export ZDOTDIR="$HOME"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export EDITOR="vim"
export VISUAL="$EDITOR"

typeset -U path
path=(
    "$HOME/.local/bin"
    "$HOME/.cargo/bin"
    $path
)
